name: passgo main workflow

on:
  push:
    branches: ["main", "healtcheck-endpoint"]

jobs:
  maven:
    name: Maven verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build with Maven
        run: chmod u+x ./mvnw && ./mvnw --batch-mode --update-snapshots verify